const DICT = {
  cardTitle: { ja: 'CLAUDE CODE MASTERY', en: 'CLAUDE CODE MASTERY' },
  level: { ja: 'Lv', en: 'Lv' },
  title: { ja: '称号', en: 'Title' },
  deviation: { ja: '推定偏差値', en: 'Est. std. score' },
  estimated: { ja: '※想定分布による推定値', en: 'estimated against an assumed distribution' },
  statSkills: { ja: 'スキル', en: 'Skills' },
  statAgents: { ja: 'エージェント', en: 'Agents' },
  statHooks: { ja: 'フック', en: 'Hooks' },
  statSessions: { ja: 'セッション', en: 'Sessions' },
  statActiveDays: { ja: '稼働日数', en: 'Active days' },
  statMemory: { ja: 'メモリー', en: 'Memory notes' },
  dashboardTitle: { ja: '詳細ダッシュボード', en: 'Detail dashboard' },
  privacyBanner: {
    ja: 'ここから下はローカル閲覧用です。スキル名・プロジェクト名を含むため、スクショ共有は非推奨。カード部分だけ共有してください。',
    en: 'Everything below is for local viewing. It contains skill and project names — avoid sharing screenshots of this section. Share only the card above.',
  },
  savePng: { ja: 'カードを PNG 保存', en: 'Save card as PNG' },
  breakdownHeading: { ja: '軸別スコア内訳', en: 'Score breakdown by axis' },
  colMetric: { ja: '指標', en: 'Metric' },
  colValue: { ja: '実測値', en: 'Value' },
  colHalf: { ja: '50点基準 (h)', en: 'Half point (h)' },
  colWeight: { ja: '重み', en: 'Weight' },
  colPoints: { ja: '得点', en: 'Points' },
  heatmapHeading: {
    ja: 'アクティビティ (transcript 保持期間内)',
    en: 'Activity (retained transcript window)',
  },
  toolsHeading: { ja: 'ツール使用 TOP15', en: 'Tool usage TOP 15' },
  skillsHeading: { ja: 'スキル発火 TOP15', en: 'Skill activations TOP 15' },
  modelsHeading: { ja: 'モデル分布', en: 'Model distribution' },
  scoringHeading: { ja: '採点方式', en: 'How scoring works' },
  scoringIntro: {
    ja: 'すべてローカルの実測値から算出。乱数なし・外部データなし。同じ環境なら必ず同じスコアになります。',
    en: 'Everything is computed from local measured values — no randomness, no external data. The same environment always yields the same score.',
  },
  scoringSatTitle: { ja: '① 各指標を0〜100点に正規化', en: '1. Normalize each metric to 0–100' },
  scoringSatBody: {
    ja: '飽和曲線。x が「50点基準 h」に達すると 50 点。0 で 0 点、増えるほど 100 に近づくが到達はしない（初心者が0に張り付かず、達人も飽和しない）。',
    en: 'A saturation curve. A metric hits 50 when x reaches its half-point h; it is 0 at 0 and approaches — but never reaches — 100. Beginners don’t flatline; power users don’t cap out.',
  },
  scoringAxisTitle: { ja: '② 軸スコア = 指標の加重和', en: '2. Axis score = weighted sum of metrics' },
  scoringAxisBody: {
    ja: '各軸は複数指標の重み付き平均。重みの合計は 1.0（上の軸別内訳の「重み」列がそれ）。',
    en: 'Each axis is a weighted average of its metrics; the weights sum to 1.0 (the “Weight” column above).',
  },
  scoringLevelTitle: { ja: '③ 総合レベル (1〜99)', en: '3. Overall level (1–99)' },
  scoringLevelBody: {
    ja: 'S = 5軸の平均。指数 0.9 で低スコア帯を少し持ち上げる。Lv99 は事実上到達不能。',
    en: 'S is the mean of the 5 axes. The 0.9 exponent lifts the low end slightly. Lv 99 is effectively unreachable.',
  },
  scoringDevTitle: { ja: '④ 推定偏差値', en: '4. Estimated standard score' },
  scoringDevBody: {
    ja: '想定分布（平均35・標準偏差15）に対する偏差値。v0.1 は推定値で、v0.2 で opt-in の実分布に置き換え予定。',
    en: 'A standard score against an assumed distribution (mean 35, sd 15). v0.1 is an estimate; v0.2 will replace it with a real opt-in distribution.',
  },
  scoringRarityTitle: { ja: '⑤ レア度（カードの輝き）', en: '5. Rarity (card foil)' },
  scoringRarityBody: {
    ja: 'レベルからカードのレア度が決まる。スコアは変えず、見た目の派手さ（★とホロの強さ）だけを左右する。',
    en: 'Level decides the card’s rarity. It changes nothing in the score — only how flashy the card looks (stars and holo intensity).',
  },
  colTier: { ja: 'レア度', en: 'Tier' },
  colStars: { ja: '★', en: 'Stars' },
  colLevelRange: { ja: 'レベル帯', en: 'Level range' },
  generatedBy: { ja: '生成', en: 'generated by' },
  localOnly: {
    ja: 'すべての解析はローカル完結 — 何も送信していません',
    en: 'All analysis is local — nothing ever leaves your machine',
  },
};

export function makeT(lang) {
  const l = lang === 'ja' ? 'ja' : 'en';
  return (key) => DICT[key]?.[l] ?? key;
}

/** Default language from environment: ja if $LANG/$LC_ALL starts with ja. */
export function detectLang(env = process.env) {
  const loc = env.LC_ALL || env.LANG || '';
  return loc.toLowerCase().startsWith('ja') ? 'ja' : 'en';
}
