const DICT = {
  cardTitle: { ja: 'CLAUDE CODE MASTERY', en: 'CLAUDE CODE MASTERY' },
  level: { ja: 'Lv', en: 'Lv' },
  title: { ja: '称号', en: 'Title' },
  deviation: { ja: '推定偏差値', en: 'Est. std. score' },
  estimated: { ja: '※想定分布による推定値', en: 'estimated against an assumed distribution' },
  statSkills: { ja: 'スキル', en: 'Skills' },
  statAgents: { ja: 'エージェント', en: 'Agents' },
  statHooks: { ja: 'フック', en: 'Hooks' },
  statSessions: { ja: 'セッション', en: 'Sessions' },
  statActiveDays: { ja: '稼働日数', en: 'Active days' },
  statMemory: { ja: 'メモリー', en: 'Memory notes' },
  dashboardTitle: { ja: '詳細ダッシュボード', en: 'Detail dashboard' },
  privacyBanner: {
    ja: 'ここから下はローカル閲覧用です。スキル名・プロジェクト名を含むため、スクショ共有は非推奨。カード部分だけ共有してください。',
    en: 'Everything below is for local viewing. It contains skill and project names — avoid sharing screenshots of this section. Share only the card above.',
  },
  savePng: { ja: 'カードを PNG 保存', en: 'Save card as PNG' },
  breakdownHeading: { ja: '軸別スコア内訳', en: 'Score breakdown by axis' },
  colMetric: { ja: '指標', en: 'Metric' },
  colValue: { ja: '実測値', en: 'Value' },
  colHalf: { ja: '50点基準 (h)', en: 'Half point (h)' },
  colWeight: { ja: '重み', en: 'Weight' },
  colPoints: { ja: '得点', en: 'Points' },
  heatmapHeading: {
    ja: 'アクティビティ (transcript 保持期間内)',
    en: 'Activity (retained transcript window)',
  },
  toolsHeading: { ja: 'ツール使用 TOP15', en: 'Tool usage TOP 15' },
  skillsHeading: { ja: 'スキル発火 TOP15', en: 'Skill activations TOP 15' },
  modelsHeading: { ja: 'モデル分布', en: 'Model distribution' },
  generatedBy: { ja: '生成', en: 'generated by' },
  localOnly: {
    ja: 'すべての解析はローカル完結 — 何も送信していません',
    en: 'All analysis is local — nothing ever leaves your machine',
  },
};

export function makeT(lang) {
  const l = lang === 'ja' ? 'ja' : 'en';
  return (key) => DICT[key]?.[l] ?? key;
}

/** Default language from environment: ja if $LANG/$LC_ALL starts with ja. */
export function detectLang(env = process.env) {
  const loc = env.LC_ALL || env.LANG || '';
  return loc.toLowerCase().startsWith('ja') ? 'ja' : 'en';
}
